DROP TABLE CALENDAR
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_CAL;

CREATE TABLE CALENDAR(
	SEQ NUMBER(8) PRIMARY KEY,
	TEAM VARCHAR2(20) NOT NULL,
	STADIUM VARCHAR2(50) NOT NULL,
	SCHE VARCHAR2(12) NOT NULL,
	WDATE DATE NOT NULL,
	OUTCOME VARCHAR2(10) NOT NULL,
	MEMO VARCHAR2(4000),
	IMGNAME VARCHAR2(20)
);

ALTER TABLE CALENDAR DROP (ID);
SELECT * FROM CALENDAR;

ALTER TABLE CALENDAR DROP CONSTRAINT FK_CAL_ID

CREATE SEQUENCE SEQ_CAL
START WITH 1
INCREMENT BY 1;

ALTER TABLE CALENDAR
ADD CONSTRAINT FK_CAL_ID FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM RESULT;

SELECT T.IMGNAME
FROM CALENDAR C, TEAM T
WHERE C.TEAM = T.NAME;

CREATE TABLE TEAM(
	NAME VARCHAR2(200) PRIMARY KEY,
	STADIUM VARCHAR2(50),
	IMGNAME VARCHAR2(20)
)


INSERT INTO TEAM
VALUES('NC', '창원', 'nc.png');
INSERT INTO TEAM
VALUES('SK', '문학', 'sk.png');
INSERT INTO TEAM
VALUES('LG', '잠실', 'lg.png');
INSERT INTO TEAM
VALUES('KT', '수원', 'kt.png');
INSERT INTO TEAM
VALUES('KIA', '광주', 'kia.png');
INSERT INTO TEAM
VALUES('삼성', '대구', 'samsung.png');
INSERT INTO TEAM
VALUES('한화', '대전', 'hanwha.png');
INSERT INTO TEAM
VALUES('두산', '잠실', 'doosan.png');
INSERT INTO TEAM
VALUES('롯데', '사직', 'lotte.png');


CREATE TABLE RESULT(
	OUTCOME VARCHAR2(20) PRIMARY KEY,
	OCNAME VARCHAR2(20),

)
INSERT INTO RESULT
VALUES('우승','win.png');
INSERT INTO RESULT
VALUES('패배','lose.png');
INSERT INTO RESULT
VALUES('경기 전','yet.png');


--조인
SELECT SEQ, ID, TEAM, C.STADIUM, SCHE, WDATE, OUTCOME, MEMO, T.IMGNAME 
FROM CALENDAR C, TEAM T
WHERE C.TEAM = T.NAME
ORDER BY SCHE ASC;

--세개 조인시키기
SELECT SEQ, ID, TEAM, CALENDAR.STADIUM, SCHE, WDATE, CALENDAR.OUTCOME, MEMO, TEAM.IMGNAME, RESULT.OCNAME
FROM CALENDAR LEFT JOIN TEAM
ON CALENDAR.TEAM = TEAM.NAME
LEFT JOIN RESULT
ON CALENDAR.OUTCOME = RESULT.OUTCOME
ORDER BY SCHE ASC;

SELECT * FROM RESULT;
SELECT * FROM CALENDAR;

UPDATE CALENDAR
SET MEMO = ''
WHERE MEMO = 'NULL';

DELETE CALENDAR
WHERE TEAM LIKE '상대팀%';

--컬럼 사이즈 변경
ALTER TABLE CALENDAR MODIFY(SCHE VARCHAR2(50));
--컬럼 전체조회
SELECT * FROM COLS WHERE TABLE_NAME = 'CALENDAR'

--데이터복구.........
INSERT INTO CALENDAR
SELECT * FROM CALENDAR AS OF TIMESTAMP(SYSTIMESTAMP - INTERVAL '5' MINUTE)

DELETE CALENDAR

INSERT INTO CALENDAR
SELECT * 
FROM CALENDAR AS OF TIMESTAMP(SYSTIMESTAMP-INTERVAL '5' MINUTE)

--drop한 테이블 살리기..............
SELECT * FROM RECYCLEBIN
FLASHBACK TABLE CALENDAR TO BEFORE DROP
--컬럼삭제
ALTER TABLE CALENDAR DROP COLUMN MEMO;
--컬럼추가
ALTER TABLE CALENDAR ADD(MEMO VARCHAR2(500) NULL);
--null허용
ALTER TABLE CALENDAR MODIFY (MEMO NULL);