DROP SEQUENCE SEQ_FREE_COMMENT;

DROP TABLE FREE_COMMENT
CASCADE CONSTRAINTS;

CREATE TABLE FREE_COMMENT(
   SEQ NUMBER(8) PRIMARY KEY,
   ID VARCHAR2(20),
   NICKNAME VARCHAR2(20),
   CONTENT VARCHAR2(1000),
   WDATE DATE,
   DEL NUMBER(1),
   BLIKE NUMBER(8),
   PARENT NUMBER(8),
   PAGE NUMBER(8)
)

CREATE SEQUENCE SEQ_FREE_COMMENT  
START WITH 1
INCREMENT BY 1;

ALTER TABLE FREE_COMMENT
ADD CONSTRAINT FK_FREE_COMMENT FOREIGN KEY(PAGE)
REFERENCES FREE_BBS(SEQ);

ALTER TABLE FREE_COMMENT
ADD CONSTRAINT FK_FREE_COMMENT2 FOREIGN KEY(ID)
REFERENCES MEMBER(ID);

SELECT * FROM FREE_COMMENT

