DROP TABLE MESSAGE
CASCADE CONSTRAINTS;

DROP SEQUENCE MESSAGE_SEQ;

CREATE TABLE MESSAGE(
	SEQ NUMBER(8) PRIMARY KEY,
	TO_ID VARCHAR2(20) NOT NULL,
	FROM_ID VARCHAR2(20) NOT NULL,
	CONTENT VARCHAR2(500) NOT NULL,
	READ NUMBER(1) NOT NULL,
	WDATE DATE NOT NULL
);

CREATE SEQUENCE MESSAGE_SEQ
START WITH 1
INCREMENT BY 1;

SELECT SEQ, TO_NICK, FROM_NICK, CONTENT, READ, WDATE
FROM (	SELECT ROW_NUMBER() OVER(ORDER BY WDATE DESC) RNUM,
			SEQ, TO_ID, M1.NICKNAME AS TO_NICK, FROM_ID, M2.NICKNAME AS FROM_NICK, CONTENT, READ, WDATE 
		FROM MESSAGE A, MEMBER M1, MEMBER M2
		WHERE A.TO_ID = M1.ID AND FROM_ID = M2.ID
			AND FROM_ID = 'yeonha94')
WHERE RNUM BETWEEN 1 AND 5;

ALTER TABLE MESSAGE
ADD CONSTRAINT FK_MESSAGE FOREIGN KEY(TO_ID)
REFERENCES MEMBER(ID);

ALTER TABLE MESSAGE
ADD CONSTRAINT FK2_MESSAGE FOREIGN KEY(FROM_ID)
REFERENCES MEMBER(ID);
