DROP TABLE PLAYER_INFO
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_PLAYER;

CREATE TABLE PLAYER_INFO(
  
   SEQ NUMBER(8) PRIMARY KEY,
   NAME VARCHAR2(70) NOT NULL,
   HEIGHT NUMBER(5) NOT NULL,
   WEIGHT NUMBER(5) NOT NULL,
   POSITION VARCHAR2(10) NOT NULL,
   PHOTONAME VARCHAR2(70) NOT NULL,
   LIKES NUMBER(5) NOT NULL
  );


CREATE SEQUENCE SEQ_PLAYER
START WITH 1
INCREMENT BY 1;

SELECT * FROM PLAYER_INFO;

INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '김규민', 188, 85, '외야수', '김규민.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '김동준', 185, 90, '투수', '김동준.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '김상수', 180, 88, '투수', '김상수.png' ,0);
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '김선기', 187, 94, '투수', '김선기.png', 0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '김성민', 181, 90, '투수', '김성민.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '김지수', 180, 81, '내야수', '김지수.png' ,0);
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '김하성', 175, 76, '내야수', '김하성.png' ,0);
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '김혜성', 182, 80, '내야수', '김혜성.png' ,0);
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '박동원', 179, 92, '포수',  '박동원.png' ,0);
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '박병호', 186, 107, '내야수', '박병호.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '박정음', 178, 75, '외야수', '박정음.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '서건창', 176, 84, '내야수', '서건창.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '송성문', 182, 85, '내야수', '송성문.png' ,0);
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '양현', 188, 70, '투수', '양현.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '에릭요키시', 188, 93, '투수', '에릭요키시.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '오주원', 184, 95, '투수', '오주원.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '윤영삼', 181, 87, '투수', '윤영삼.png' ,0);

INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '이승호', 187, 93, '투수', '이승호.png' ,0);
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '이정후', 185, 75, '외야수', '이정후.png' ,0);
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '이지영', 178, 83, '포수', '이지영.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '임병욱', 185, 84, '외야수', '임병욱.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '제리샌즈', 193, 105, '외야수', '제리샌즈.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '제이크브리검', 190, 90, '투수', '제이크브리검.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '조상우', 186, 97, '투수', '조상우.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '주효상', 182, 85, '포수', '주효상.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '최원태', 184, 93, '투수', '최원태.png',0 );
INSERT INTO PLAYER_INFO VALUES (SEQ_PLAYER.NEXTVAL, '한현희', 182, 95, '투수', '한현희.png',0 );



