DROP TABLE LIKE_BBS
CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_LIKE;

CREATE TABLE LIKE_BBS(
SEQ NUMBER(8) PRIMARY KEY,
ID VARCHAR2(20) NOT NULL,
ACOUNT NUMBER(8) NOT NULL
);

CREATE SEQUENCE SEQ_LIKE
START WITH 1
INCREMENT BY 1;

ALTER TABLE LIKE_BBS
ADD CONSTRAINT FK_LIKE_ACOUNT FOREIGN KEY(ACOUNT)
REFERENCES SELL_BBS(SEQ);

SELECT * FROM LIKE_BBS;

SELECT SEQ, B.ID, TITLE, CONTENT, RCOUNT, B.ACOUNT, WDATE, DEL, PRICE, CATEGORY, PCATEGORY, COMPLETE, REPORT, FILENAME, NICKNAME
FROM MEMBER M, ( SELECT B.SEQ, B.ID, TITLE, CONTENT, RCOUNT, B.ACOUNT, WDATE, DEL, 
					PRICE, CATEGORY, PCATEGORY, COMPLETE, REPORT, FILENAME 
					FROM SELL_BBS B, (SELECT ACOUNT FROM LIKE_BBS WHERE ID='yeonha94') C
					WHERE B.SEQ = C.ACOUNT AND B.DEL = 0 ) B
WHERE M.ID = B.ID;
